/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bottiger_podcast_Player_sonic_Sonic */

#ifndef _Included_org_bottiger_podcast_Player_sonic_Sonic
#define _Included_org_bottiger_podcast_Player_sonic_Sonic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    initNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_initNative
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_closeNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    flushNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_flushNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setSampleRateNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setSampleRateNative
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getSampleRateNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getSampleRateNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setNumChannelsNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setNumChannelsNative
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getNumChannelsNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getNumChannelsNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setPitchNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setPitchNative
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getPitchNative
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getPitchNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setSpeedNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setSpeedNative
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getSpeedNative
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getSpeedNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setRateNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setRateNative
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getRateNative
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getRateNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setChordPitchNative
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setChordPitchNative
        (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getChordPitchNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getChordPitchNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    putBytesNative
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_putBytesNative
        (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    receiveBytesNative
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_receiveBytesNative
        (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    availableBytesNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_availableBytesNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    setVolumeNative
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_setVolumeNative
        (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_bottiger_podcast_Player_sonic_Sonic
 * Method:    getVolumeNative
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_bottiger_podcast_Player_sonic_Sonic_getVolumeNative
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
